files:
  - source: /GlucoseDirect/en.lproj/InfoPlist.strings
    translation: /GlucoseDirect/%osx_locale%.lproj/InfoPlist.strings
  - source: /GlucoseDirect/Resources/en.lproj/Localizable.strings
    translation: /GlucoseDirect/Resources/%osx_locale%.lproj/Localizable.strings
  - source: /GlucoseDirect/Resources/Settings.bundle/en.lproj/Root.strings
    translation: /GlucoseDirect/Resources/Settings.bundle/%osx_locale%.lproj/Root.strings
