files:
  - source: /App/en.lproj/InfoPlist.strings
    translation: /App/%osx_locale%.lproj/InfoPlist.strings
  - source: /AppWidgets/en.lproj/InfoPlist.strings
    translation: /AppWidgets/%osx_locale%.lproj/InfoPlist.strings
  - source: /AppLibrary/en.lproj/Localizable.strings
    translation: /AppLibrary/%osx_locale%.lproj/Localizable.strings

